\documentclass{article}

% Yihui's knitrsettings from example https://github.com/yihui/knitr/blob/master/inst/examples/knitr-minimal.Rnw

\usepackage[sc]{mathpazo}
%\usepackage[T1]{fontenc}
\usepackage{geometry}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\setcounter{secnumdepth}{2}
\setcounter{tocdepth}{2}
\usepackage{url}
\usepackage[unicode=true,pdfusetitle,
 bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2,
 breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=false]
 {hyperref}
\hypersetup{
 pdfstartview={XYZ null null 1}}
\usepackage{breakurl}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<defaults, echo=FALSE,results=hide, message=FALSE, cache=FALSE>>=
if (!exists('.knitr.title')) .knitr.title = 'Immigrant, Refugee, and Migrant Health Branch'
if (!exists('.knitr.author')) .knitr.author = Sys.info()['user']
.knitr.title= 'Epidemiology Book of the Immigrant, Refugee, and Migrant Health Branch'
.knitr.author = 'John A. Painter, DVM, MS'

# Set options for report
opts_chunk$set(comment = "")
opts_chunk$set(echo = TRUE)
opts_chunk$set(message = TRUE)
opts_chunk$set(tidy = TRUE)

# this is equivalent to \SweaveOpts{...}
opts_chunk$set(fig.path='images', fig.align='center', fig.show='hold')
options(replace.assign=TRUE,width=90)
@

\title{\Sexpr{.knitr.title}}
\author{\Sexpr{.knitr.author}%
\thanks{Epidemiology Team: John A. Painter (lead), Kendra Cuffe, Sasi Jonnalagadda, Yecai Liu, Rossanne Philen, Zanju Wang, Meghan Weems.%
}}

\maketitle
\tableofcontents  % inserts 'Table of contents' 
\listoftables  % inserts 'List of Tables' (numbers and captions)
\listoffigures % inserts 'List of Figures' (numbers and captions)

\section{long-term trends}

- incoming refugees

- Heatmap of Refugee Arrivals
<<Heatmap>>=
# Load spreadsheet
require(XLConnect)
wb <- loadWorkbook("//cdc/project/ccid_ncpdcid_dgmq/IRMH/DNA/DNAproduction_Notifications.xlsx")
# list of sheets:
# TbByStateYear, TbByPresentCountryYear, 
# RefugeesByStateYear, RefugeesByLocationYear, RefugeesArrivalsByRegionByDay, RefugeesByStateNationality

# Refugee arrivals by day
####
RefugeeArrivalDay <- readWorksheet(wb, sheet = "RefugeesArrivalsByRegionByDay", startRow=4, startCol=1, header = TRUE) # start row is row with cell "Row Labels"
str(RefugeeArrivalDay)

# Make a dataframe
dat<-RefugeeArrivalDay
names(dat)[1] <- "date"
#get date (Wednesday, March 2 2012) into R 
dat$date <- strptime(dat$date, format="%A, %B %d %Y")

# We will facet by year ~ month, and each subgraph will
# show week-of-month versus weekday
# the year is simple
dat$year<-as.numeric(as.POSIXlt(dat$date)$year+1900)
# limit to years >2002
dat <- dat[dat$year>2002 & !is.na(dat$year),]

# the month too 
dat$month<-as.numeric(as.POSIXlt(dat$date)$mon+1)
# but turn months into ordered facors to control the appearance/ordering in the presentation
dat$monthf<-factor(dat$month,levels=as.character(1:12),labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),ordered=TRUE)
# the day of week is again easily found
dat$weekday = as.POSIXlt(dat$date)$wday
# again turn into factors to control appearance/abbreviation and ordering
# I use the reverse function rev here to order the week top down in the graph
# you can cut it out to reverse week order
dat$weekdayf<-factor(dat$weekday,levels=rev(0:6),labels=rev(c("Mon","Tue","Wed","Thu","Fri","Sat","Sun")),ordered=TRUE)

# the monthweek part is a bit trickier
# first a factor which cuts the data into month chunks
require(zoo)
dat$yearmonth<-as.yearmon(dat$date)
dat$yearmonthf<-factor(dat$yearmonth)
# then find the "week of year" for each day
dat$week <- as.numeric(format(dat$date,"%W"))
# and now for each monthblock we normalize the week to start at 1 
dat<-ddply(dat,.(yearmonthf),transform,monthweek=1+week-min(week))
#convert Grand.Total to total; remove comma from values >1,000
dat$total <- as.numeric(gsub(",","", dat$Grand.Total))

#Reshape data
require(reshape)
dat.melt = melt(dat, id=c("year", "monthf", "monthweek"), measure.vars=c(2:7), variable_name="region", na.rm=TRUE)

# examine results
library(Hmisc)  # for weighted tables
x.tab = xtabs(value~year+region, data=dat.melt)

require(xtable)
xtable(x.tab, caption ="Table of Refugee Arrivals by Region of Origin", label ="Region-Table", digits = 4)

require(ggplot2)
# ggplot( dat.melt, aes(monthweek, region, fill=region , alpha=value ) ) + 
#   geom_tile(colour="white") + facet_grid(year~monthf) +
#   opts(title = "Refugee Arrivals") +  xlab("Week of Month") + ylab("Region")
@


- Immigrants with Class B Conditions
<<incoming-refugees>>=
# require(knitr)
# read_chunk("Calendar heatmap of refugee arrivals.R")
@

- state locations

- secondary migration

- ltbi rates among children (B2) and adults (follow-up exams of B1s)

- TB prevalence by age-group, by visa type, with annual percent change
-- It seems to me that the 2.9 perc annual rate of infection estimated from the Vietnamese applicants would make most of the TB  infections more than 2 yrs remote, except in the very young. Refugees might be in a totally different situation. 

- the proportion of refugees that adjust status—and therefore have completed vx—by ethnicity, age, etc.

\section{The most recent 12 months}



\section{Special views of data}

- Percent class b, by country
<<PercentClassBArrived, message=FALSE, echo=TRUE, results='markup', tidy=TRUE>>=
read_chunk("C:/Users/bzp3/Desktop/Linkage/PhData/PercentClassBArrived.R")
@

- linkage project--time to TB diagnosis

- qft summaries


\section{Computing Environment}

The R session information (including the OS info, R version and all
packages used):
<<session-info, cache=FALSE>>=
sessionInfo()
Sys.time()
@

\end{document}